version: '3'

services:
    lolo-php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        depends_on:
            - lolo-firefox
        volumes:
            - ./:/lolo-promo

    lolo-firefox:
        platform: 'linux/amd64'
        image: selenium/standalone-firefox:latest
        shm_size: 2gb
        ports:
            - '4444:4444'
            - '7900:7900'
        environment:
            - SE_VNC_NO_PASSWORD=1
        depends_on:
            - lolo-postgres

    lolo-postgres:
        image: postgres:15.1-alpine
        volumes:
            - lolo-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: lolo
            POSTGRES_PASSWORD: lolo
            POSTGRES_DB: lolo
        ports:
            - '5432:5432'

volumes:
    lolo-postgres:
